// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJypus4mYW4Dr7iAuCzKXRFWhqtsWCyxo',
    appId: '1:774939199403:web:f62079fc8f08dff82ff4ee',
    messagingSenderId: '774939199403',
    projectId: 'instagram-clone-b21bf',
    authDomain: 'instagram-clone-b21bf.firebaseapp.com',
    storageBucket: 'instagram-clone-b21bf.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAU1OopyMTKaUnrArMh_6_TvjrQOr-qO2c',
    appId: '1:774939199403:android:eac23aa8fa9880df2ff4ee',
    messagingSenderId: '774939199403',
    projectId: 'instagram-clone-b21bf',
    storageBucket: 'instagram-clone-b21bf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCV6Adxf3fHcm0sFbrfGK6zOjdu8vWV1_o',
    appId: '1:774939199403:ios:ec507fbfa6bccb292ff4ee',
    messagingSenderId: '774939199403',
    projectId: 'instagram-clone-b21bf',
    storageBucket: 'instagram-clone-b21bf.appspot.com',
    iosClientId: '774939199403-pq2dagneh3rs1hu2v4986f2mhm5b5h8l.apps.googleusercontent.com',
    iosBundleId: 'com.purboindra.instagramClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCV6Adxf3fHcm0sFbrfGK6zOjdu8vWV1_o',
    appId: '1:774939199403:ios:ec507fbfa6bccb292ff4ee',
    messagingSenderId: '774939199403',
    projectId: 'instagram-clone-b21bf',
    storageBucket: 'instagram-clone-b21bf.appspot.com',
    iosClientId: '774939199403-pq2dagneh3rs1hu2v4986f2mhm5b5h8l.apps.googleusercontent.com',
    iosBundleId: 'com.purboindra.instagramClone',
  );
}
